// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC57tfVm35uZjktwu21vrwPYCKsa25BezE',
    appId: '1:1009657520905:web:2285cd09fcb8b5e43ae9d8',
    messagingSenderId: '1009657520905',
    projectId: 'notes-48840',
    authDomain: 'notes-48840.firebaseapp.com',
    storageBucket: 'notes-48840.firebasestorage.app',
    measurementId: 'G-LVVSN3T08N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-K9UVhPQb4tXCMPIQK2WAB0K-pyrgDBs',
    appId: '1:1009657520905:android:ba74ef999221e83b3ae9d8',
    messagingSenderId: '1009657520905',
    projectId: 'notes-48840',
    storageBucket: 'notes-48840.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC57tfVm35uZjktwu21vrwPYCKsa25BezE',
    appId: '1:1009657520905:web:e79f18fb9ff720643ae9d8',
    messagingSenderId: '1009657520905',
    projectId: 'notes-48840',
    authDomain: 'notes-48840.firebaseapp.com',
    storageBucket: 'notes-48840.firebasestorage.app',
    measurementId: 'G-XPGB9N17G4',
  );
}