// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4F_drrXwW4ElYiw9Fd_AP_bEFkiy4XbU',
    appId: '1:191611950738:web:ff1e7799a5e85b4e0fb84b',
    messagingSenderId: '191611950738',
    projectId: 'notes-f0a92',
    authDomain: 'notes-f0a92.firebaseapp.com',
    storageBucket: 'notes-f0a92.firebasestorage.app',
    measurementId: 'G-BJZQ5WVR5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf5vOsx_H18-uNTIq3lrV074wJdHhmC80',
    appId: '1:191611950738:android:1688e6d6b928e7370fb84b',
    messagingSenderId: '191611950738',
    projectId: 'notes-f0a92',
    storageBucket: 'notes-f0a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6YdOHcmuLbfrwLLlwJzHl_y0nLp5veMc',
    appId: '1:191611950738:ios:d8232088bcf2ecb80fb84b',
    messagingSenderId: '191611950738',
    projectId: 'notes-f0a92',
    storageBucket: 'notes-f0a92.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6YdOHcmuLbfrwLLlwJzHl_y0nLp5veMc',
    appId: '1:191611950738:ios:d8232088bcf2ecb80fb84b',
    messagingSenderId: '191611950738',
    projectId: 'notes-f0a92',
    storageBucket: 'notes-f0a92.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4F_drrXwW4ElYiw9Fd_AP_bEFkiy4XbU',
    appId: '1:191611950738:web:ffba0b132655d6250fb84b',
    messagingSenderId: '191611950738',
    projectId: 'notes-f0a92',
    authDomain: 'notes-f0a92.firebaseapp.com',
    storageBucket: 'notes-f0a92.firebasestorage.app',
    measurementId: 'G-7MHG5KXW9G',
  );
}
