// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANISGNTTt8db-bYUO2ndngymdsvzlQ48w',
    appId: '1:229245408327:web:78e56e3365d68648978d62',
    messagingSenderId: '229245408327',
    projectId: 'daftarbelanja-ce333',
    authDomain: 'daftarbelanja-ce333.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-ce333-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-ce333.firebasestorage.app',
    measurementId: 'G-HNCE0PRCBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAljGiXmtIULHEtP58h-ohSzf737QXxb0',
    appId: '1:229245408327:android:d36e3879046a5099978d62',
    messagingSenderId: '229245408327',
    projectId: 'daftarbelanja-ce333',
    databaseURL: 'https://daftarbelanja-ce333-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-ce333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGkHLUFJR02rLhpHuxlp-0XETmVPHTg48',
    appId: '1:229245408327:ios:c803e7bbde90ba09978d62',
    messagingSenderId: '229245408327',
    projectId: 'daftarbelanja-ce333',
    databaseURL: 'https://daftarbelanja-ce333-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-ce333.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGkHLUFJR02rLhpHuxlp-0XETmVPHTg48',
    appId: '1:229245408327:ios:c803e7bbde90ba09978d62',
    messagingSenderId: '229245408327',
    projectId: 'daftarbelanja-ce333',
    databaseURL: 'https://daftarbelanja-ce333-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-ce333.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANISGNTTt8db-bYUO2ndngymdsvzlQ48w',
    appId: '1:229245408327:web:b56701e82133569f978d62',
    messagingSenderId: '229245408327',
    projectId: 'daftarbelanja-ce333',
    authDomain: 'daftarbelanja-ce333.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-ce333-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-ce333.firebasestorage.app',
    measurementId: 'G-LY03XZTJ35',
  );
}
