// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7hMScIo5CIGXu6ZrndTV6Q00QbtizUE',
    appId: '1:169390979251:web:0d45b350e6fc60292918c6',
    messagingSenderId: '169390979251',
    projectId: 'cloud-message-22bd4',
    authDomain: 'cloud-message-22bd4.firebaseapp.com',
    storageBucket: 'cloud-message-22bd4.firebasestorage.app',
    measurementId: 'G-PPZJV5VGZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0bGIZ8nXjWYcNvrvbG90-LjSI95Nyy0M',
    appId: '1:169390979251:android:dde2d73faa5faff72918c6',
    messagingSenderId: '169390979251',
    projectId: 'cloud-message-22bd4',
    storageBucket: 'cloud-message-22bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyQdHTZxOEtHq6unbI6xaQ-xoR9JTk6k',
    appId: '1:169390979251:ios:d8706d516cc077e82918c6',
    messagingSenderId: '169390979251',
    projectId: 'cloud-message-22bd4',
    storageBucket: 'cloud-message-22bd4.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnyQdHTZxOEtHq6unbI6xaQ-xoR9JTk6k',
    appId: '1:169390979251:ios:d8706d516cc077e82918c6',
    messagingSenderId: '169390979251',
    projectId: 'cloud-message-22bd4',
    storageBucket: 'cloud-message-22bd4.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl7hMScIo5CIGXu6ZrndTV6Q00QbtizUE',
    appId: '1:169390979251:web:9e9f86604e4302b82918c6',
    messagingSenderId: '169390979251',
    projectId: 'cloud-message-22bd4',
    authDomain: 'cloud-message-22bd4.firebaseapp.com',
    storageBucket: 'cloud-message-22bd4.firebasestorage.app',
    measurementId: 'G-1W9C7G8BGK',
  );

}