// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KuNoBdxL-fY35ahA3MapraG85OBBiXU',
    appId: '1:1073306177852:web:1d1f7477a5876815d8ce39',
    messagingSenderId: '1073306177852',
    projectId: 'mdp-gold-e2b7c',
    authDomain: 'mdp-gold-e2b7c.firebaseapp.com',
    storageBucket: 'mdp-gold-e2b7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4yTaxI3IikMPu-gzB0h21lkrEA5JH_yg',
    appId: '1:1073306177852:android:d36ffebd781213a7d8ce39',
    messagingSenderId: '1073306177852',
    projectId: 'mdp-gold-e2b7c',
    storageBucket: 'mdp-gold-e2b7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQ1RQtL20eqidQz5OLzaVnfX7ttOZiDE',
    appId: '1:1073306177852:ios:9b6f2ce6ff6f7f63d8ce39',
    messagingSenderId: '1073306177852',
    projectId: 'mdp-gold-e2b7c',
    storageBucket: 'mdp-gold-e2b7c.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQ1RQtL20eqidQz5OLzaVnfX7ttOZiDE',
    appId: '1:1073306177852:ios:9b6f2ce6ff6f7f63d8ce39',
    messagingSenderId: '1073306177852',
    projectId: 'mdp-gold-e2b7c',
    storageBucket: 'mdp-gold-e2b7c.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1KuNoBdxL-fY35ahA3MapraG85OBBiXU',
    appId: '1:1073306177852:web:8e2f725023415aebd8ce39',
    messagingSenderId: '1073306177852',
    projectId: 'mdp-gold-e2b7c',
    authDomain: 'mdp-gold-e2b7c.firebaseapp.com',
    storageBucket: 'mdp-gold-e2b7c.firebasestorage.app',
  );

}